#! /bin/sh

ghci -isrc \
     -idist/build/autogen \
     -XTypeFamilies \
     -XFlexibleInstances \
     -XImplicitParams \
     -XNoMonomorphismRestriction \
     -XStandaloneDeriving \
     -XGeneralizedNewtypeDeriving \
     -XScopedTypeVariables \
     -XFlexibleContexts \
     -XConstraintKinds \
     $@
