#! /bin/sh

ghci src/Vision.hs -isrc -idist/build/autogen -XTypeFamilies -XFlexibleInstances -XDatatypeContexts -XImplicitParams -XNoMonomorphismRestriction -XStandaloneDeriving -XGeneralizedNewtypeDeriving -XScopedTypeVariables -XFlexibleContexts -XConstraintKinds
